//! Convergence plan T03 — navigation ingress and work contract (E0, E1).
//!
//! Frozen target: `.agents/specs/e2e-preregistration.yml`. The ingress gate
//! (`accept_work_requested`) enforces: exclusive godspeed_agent producer
//! authority, canonical non-placeholder identity bound to the local
//! resolution, and complete work contracts. The cross-language fixture is
//! generated by GodSpeed-Agent's real projector (see
//! godspeed_agent/tests/test_canonical_events.py).

use serde_json::{json, Value};
use sha2::{Digest, Sha256};

use swe_seed_core::federation::{
    accept_work_requested, fallback_hash, make_event, verify_declared_hash, ConsumeError, Envelope,
};

fn digest(seed: &[u8]) -> String {
    format!("{:x}", Sha256::digest(seed))
}

fn model_hash() -> String {
    digest(b"t03-model")
}

/// Forge an envelope with an arbitrary source stamp (the attack primitive).
fn forge(event_type: &str, source_agent: &str, hash: &str) -> Envelope {
    let mut env = make_event(event_type, json!({}).as_object().unwrap().clone(), hash);
    env.source_agent = source_agent.to_string();
    env
}

/// A contractually complete WorkRequested payload.
fn full_payload() -> serde_json::Map<String, Value> {
    json!({
        "work_request_id": "wr-t03",
        "affordance_id": "aff-1",
        "desired_outcome": "deploy via blue-green",
        "settlement_criteria": ["health check green", "zero-downtime observed"],
    })
    .as_object()
    .unwrap()
    .clone()
}

fn valid_envelope() -> Envelope {
    godspeed_envelope(full_payload(), &model_hash())
}

/// Properly stamped envelope (godspeed_agent is the only lawful producer).
fn godspeed_envelope(payload: serde_json::Map<String, Value>, hash: &str) -> Envelope {
    let mut env = make_event("WorkRequested", payload, hash);
    env.source_agent = "godspeed-agent".into();
    env
}

// --- E1 happy path -----------------------------------------------------------

#[test]
fn e1_complete_work_contract_is_accepted() {
    let contract = accept_work_requested(&valid_envelope(), &model_hash()).unwrap();
    assert_eq!(contract.work_request_id, "wr-t03");
    assert_eq!(contract.affordance_id, "aff-1");
    assert_eq!(contract.desired_outcome, "deploy via blue-green");
    assert_eq!(contract.settlement_criteria.len(), 2);
}

// --- frozen falsifier: producer direction/authority --------------------------

#[test]
fn t03_non_godspeed_producer_cannot_enter_work_contracts() {
    for forger in ["swe-seed", "context-kernel", "realitytrace", "mystery"] {
        let mut forged = make_event("WorkRequested", full_payload(), &model_hash());
        forged.source_agent = forger.into();
        let err = accept_work_requested(&forged, &model_hash()).unwrap_err();
        assert!(
            matches!(err, ConsumeError::ProducerAuthority(_)),
            "forger {forger} must be rejected: {err}"
        );
    }
}

// --- frozen falsifier: destination-only inputs -------------------------------

#[test]
fn t03_destination_only_without_affordance_is_rejected() {
    let mut payload = full_payload();
    payload.remove("affordance_id");
    let err = accept_work_requested(&godspeed_envelope(payload, &model_hash()), &model_hash())
        .unwrap_err();
    assert!(
        matches!(err, ConsumeError::DestinationOnly { ref field } if field == "affordance_id"),
        "{err}"
    );
}

#[test]
fn t03_destination_only_without_desired_outcome_is_rejected() {
    let mut payload = full_payload();
    payload.insert("desired_outcome".into(), json!(""));
    let err = accept_work_requested(&godspeed_envelope(payload, &model_hash()), &model_hash())
        .unwrap_err();
    assert!(matches!(err, ConsumeError::DestinationOnly { .. }), "{err}");
}

#[test]
fn t03_work_request_without_settlement_criteria_is_rejected() {
    // The ungrounded-objective falsifier: no observable completion criteria.
    for criteria in [json!([]), json!(null), json!(["", "   "])] {
        let mut payload = full_payload();
        payload.insert("settlement_criteria".into(), criteria);
        let err = accept_work_requested(&godspeed_envelope(payload, &model_hash()), &model_hash())
            .unwrap_err();
        assert!(
            matches!(err, ConsumeError::DestinationOnly { .. }),
            "empty criteria must reject: {err}"
        );
    }
}

#[test]
fn t03_missing_correlation_is_rejected() {
    let mut payload = full_payload();
    payload.remove("work_request_id");
    let err = accept_work_requested(&godspeed_envelope(payload, &model_hash()), &model_hash())
        .unwrap_err();
    assert!(matches!(err, ConsumeError::DestinationOnly { .. }), "{err}");
}

// --- domain identity cross-wire / placeholders --------------------------------

#[test]
fn t03_cross_wired_domain_identity_is_rejected() {
    // Valid envelope, but SWE_SEED resolves a DIFFERENT model locally.
    let local_model = digest(b"t03-local-model");
    let err = accept_work_requested(&valid_envelope(), &local_model).unwrap_err();
    assert!(matches!(err, ConsumeError::HashDrift { .. }), "{err}");
}

#[test]
fn t03_fallback_pseudo_hash_cannot_settle_a_work_contract() {
    let mut payload = full_payload();
    payload.insert("domain_model_hash".into(), json!(fallback_hash()));
    let err = accept_work_requested(
        &godspeed_envelope(payload, &fallback_hash()),
        &fallback_hash(),
    )
    .unwrap_err();
    assert!(matches!(err, ConsumeError::Identity(_)), "{err}");

    let all_zero = "0".repeat(64);
    let env = forge("WorkRequested", "godspeed-agent", &all_zero);
    assert!(accept_work_requested(&env, &all_zero).is_err());

    // And the structural gate agrees:
    assert!(verify_declared_hash(&fallback_hash()).is_err());
}

// --- E0 producer sanity --------------------------------------------------------

#[test]
fn e0_desired_direction_produced_only_by_external_environment() {
    use swe_seed_core::federation::{agent_id, authoritative_producer};
    assert_eq!(
        authoritative_producer("DesiredDirection"),
        Some(agent_id::EXTERNAL_ENVIRONMENT)
    );
    let gsa_stamped = forge("DesiredDirection", "godspeed-agent", &model_hash());
    assert!(swe_seed_core::federation::validate_producer(&gsa_stamped).is_err());
}

// --- cross-language fixture: GSA's real projector output ----------------------

#[test]
fn t03_golden_fixture_from_gsa_projector_is_accepted() {
    let root = std::env::var("GODSPEED_AGENT_ROOT").unwrap_or_else(|_| {
        format!(
            "{}/godspeed_agent",
            std::env::var("HOME").unwrap_or_default()
        )
    });
    let fixture = std::path::Path::new(&root).join("tests/fixtures/t03_work_requested.json");
    let Ok(body) = std::fs::read_to_string(&fixture) else {
        eprintln!(
            "SKIP: fixture not found at {} (run godspeed_agent pytest to generate)",
            fixture.display()
        );
        return;
    };
    let envelope: Envelope = serde_json::from_str(&body)
        .expect("GSA projector output must decode as a canonical v1 envelope");
    let contract = accept_work_requested(&envelope, envelope.domain_model_hash().expect("hash"))
        .expect("GSA-projected WorkRequested must pass the canonical ingress gate");
    assert!(!contract.settlement_criteria.is_empty());
    assert_eq!(contract.affordance_id, "aff-blue-green-001");
}
