//! federation_verify_sea: SWE_Seed verifies a SEA-Forge-signed AuthorityChecked
//! envelope (the mutual direction). The vector at
//! `tests/fixtures/sea-authority-vector.json` is generated by SEA's Python
//! `signing.py` (sea-test key 0x02); SWE_Seed's Rust verifier must accept it.

use swe_seed_core::federation::{
    canonical_signing_string, public_key_from_b64, verify_envelope, Envelope,
};

fn root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

#[derive(serde::Deserialize)]
struct Vector {
    public_key_b64: String,
    namespace: String,
    event_type: String,
    occurred_at: String,
    payload: serde_json::Value,
    canonical_signing_string: String,
    signature_b64: String,
}

#[test]
fn swe_seed_verifies_sea_authority_checked() {
    let v: Vector = serde_json::from_str(
        &std::fs::read_to_string(root().join("tests/fixtures/sea-authority-vector.json")).unwrap(),
    )
    .unwrap();

    // Rust's canonical string must match SEA's.
    let canon = canonical_signing_string(&v.namespace, &v.event_type, &v.occurred_at, &v.payload);
    assert_eq!(
        canon, v.canonical_signing_string,
        "canonical string drift (SEA→SWE_Seed)"
    );

    let envelope = Envelope {
        event_id: String::new(),
        event_type: v.event_type.clone(),
        namespace: v.namespace.clone(),
        occurred_at: v.occurred_at.clone(),
        payload: v.payload.clone(),
    };
    let pk = public_key_from_b64(&v.public_key_b64).unwrap();
    assert!(
        verify_envelope(&envelope, &v.signature_b64, &pk).is_ok(),
        "SWE_Seed must verify SEA's signed AuthorityChecked envelope"
    );

    // A forged result ('deny' instead of 'allow') fails verification.
    let mut forged = envelope.clone();
    forged.payload["result"] = serde_json::json!("deny");
    assert_eq!(
        verify_envelope(&forged, &v.signature_b64, &pk),
        Err(swe_seed_core::federation::VerifyError::InvalidSignature),
        "a tampered SEA envelope must fail verification"
    );
}
